version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: rooms_database
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=rooms_database
    volumes:
      - rooms_data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'
    networks:
      -  internal_network
#
#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: username@admin.com
#      PGADMIN_DEFAULT_PASSWORD: pass
#    ports:
#      - '5050:80'

networks:
  internal_network:
    name: internal_network
    driver: bridge

volumes:
  rooms_data:
    driver: local
