version: "3.7"

services:

#  reservation-service:
#    build: RoomReservation.ReservationService/.
#    image: "reservation-service:0.0.1-SNAPSHOT"
#    container_name: reservation-service
#    ports:
#      - '8081:8081'
#    networks:
#      - internal_network
#    depends_on:
#      - reservations_database
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/example
#      - SPRING_DATASOURCE_USERNAME=example
#      - SPRING_DATASOURCE_PASSWORD=example
#
#  room-service:
#    build: RoomReservation.RoomsService/.
#    image: "room-service:0.0.1-SNAPSHOT"
#    container_name: room-service
#    ports:
#      - '8082:8080'
#    networks:
#      - internal_network

#  swagger-ui:
#    build: ./swagger-ui
#    ports:
#      - "8080:80"
#    networks:
#      - internal_network
#    volumes:
#      - RoomReservation.RoomsService/swagger.json:/usr/share/nginx/html/roomService.json
#      - RoomReservation.ReservationService/swagger.json:/usr/share/nginx/html/reservationService.json
#    depends_on:
#      - reservation-service
#      - room-service


#  rooms_database:
#    image: postgres:latest
#    container_name: rooms_database
#    restart: always
#    environment:
#      - POSTGRES_USER=username
#      - POSTGRES_PASSWORD=pass
#      - POSTGRES_DB=rooms
#    volumes:
#      - rooms_data:/var/lib/postgresql/rooms_data:rw
#    ports:
#      - '5432:5432'
#    networks:
#      -  internal_network
#
#
#  reservations_database:
#    image: postgres:latest
#    container_name: reservations_database
#    restart: always
#    environment:
#      - POSTGRES_USER=username
#      - POSTGRES_PASSWORD=pass
#      - POSTGRES_DB=reservations
#    volumes:
#      - reservations_data:/var/lib/postgresql/reservations_data:rw
#    ports:
#      - '5433:5432'
#    networks:
#      -  internal_network

  reservations_database_mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reservations_mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  rooms_database_mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rooms_mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

#
#  mysqldb:
#    image: mysql:8
#    networks:
#      - employee-mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=reservations

#networks:
#  internal_network:
#    name: internal_network
#    driver: bridge

#volumes:
#  rooms_data:
#    driver: local
#  reservations_data:
#    driver: local
