version: "3.7"

services:
  rooms_database:
    image: rooms_database:latest
    container_name: rooms_database
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=rooms
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'
    networks:
      -  internal_network

  reservations_database:
    image: reservations_database:latest
    container_name: reservations_database
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=reservations
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    ports:
      - '5433:5432'
    networks:
      -  internal_network

networks:
  internal_network:
    name: internal_network
    driver: bridge

volumes:
  pg_data:
    driver: local
