version: "3.7"

services:
  postgres:
    # Please check this blog post
    # https://geshan.com.np/blog/2021/12/docker-postgres/
    # https://www.youtube.com/watch?v=_oqSGs3rrf8
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=database
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      -  internal_network

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '5050:80' ## map TCP (5050) port on the docker host, to internal container port (80)

networks:
  internal_network:
    name: internal_network
    driver: bridge

volumes:
  pg_data:
    driver: local
